//
// Generated file, do not edit! Created by nedtool 5.2 from pack.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PACK_M_H
#define __PACK_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>pack.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Pack
 * {
 *     int pid;
 *     string type;
 *     int sid;
 *     int did;
 * }
 * </pre>
 */
class Pack : public ::omnetpp::cPacket
{
  protected:
    int pid;
    ::omnetpp::opp_string type;
    int sid;
    int did;

  private:
    void copy(const Pack& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Pack&);

  public:
    Pack(const char *name=nullptr, short kind=0);
    Pack(const Pack& other);
    virtual ~Pack();
    Pack& operator=(const Pack& other);
    virtual Pack *dup() const override {return new Pack(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPid() const;
    virtual void setPid(int pid);
    virtual const char * getType() const;
    virtual void setType(const char * type);
    virtual int getSid() const;
    virtual void setSid(int sid);
    virtual int getDid() const;
    virtual void setDid(int did);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Pack& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Pack& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACK_M_H

